### PR TITLE
remove token requirement for clientSecret. Accept auth0 example values

### LINKED ISSUE #3: Config values differ from auth0 example
The config values you verify against for the options differ from those provided by auth0. This can lead to some confusion so consistency there might be good, if not documenting the differences might be best.

The values that differ are 

| Auth0 | auth0-lock-webapp |
| --- | --- |
| clientID | clientId |
| callbackURL | redirectUri |

Additionally `clientSecret` can't be restricted to `token()`  because secrets can include - (dash) and token only does alpha numeric and underscore.

`clientSecret: joi.string().token().required()`

I'm happy to provide a PR just wanted to know your thoughts on both issues before I put in the time :)

### PR DESCRIPTION
**Pull request by evilpacket**
Fixes #3

### CODE REVIEW

**Comment by phated** [comment]
Nice implementation but I just tried your fork in our application and it doesn't seem to work.  I think that Joi no longer mutates the object passed in when using `joi.assert` or `joi.validate` so the `joi.assert` on line 28 might need to be switched to `joi.validate` and the results of successful validation need to be assigned to the `options`.

**Comment by evilpacket** [comment]
@phated yup I was just testing some things and found out it's a disaster lol. I'll figure out what I'm doing wrong and fix it up.

**Comment by phated** [comment]
Thanks for sending this.  I tweaked the code to use `joi.validate` and got this working.  Published as 0.3.0

**Comment by evilpacket** [comment]
Thanks sorry I had not had a chance to get back to it to fix it. Appreciate you doing so

**Comment by phated** [comment]
Np. Just cleaning out the inbox before the weekend!

**Pull request merged**
